name: ci
on:
  - push
  - pull_request

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'pnpm'
            - name: Setup project
              run: pnpm install
            - name: Compile project
              run: pnpm build
            - name: Run ui tests
              run: pnpm test
            - name: Build std
              run: echo 'mod std; fn main() {}' > main.chg && pnpm compile main.chg
            - name: Build stage1 compiler
              working-directory: self
              run: node .. main.chg
